"""add atribute is_activate

Revision ID: 4ca5d8e3796a
Revises: e0970c86c22c
Create Date: 2025-10-30 18:42:37.569636

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ca5d8e3796a'
down_revision = 'e0970c86c22c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('touristinfo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('touristinfo', schema=None) as batch_op:
        batch_op.drop_column('is_active')

    # ### end Alembic commands ###
