"""add atribute promedio

Revision ID: e0970c86c22c
Revises: 
Create Date: 2025-10-30 18:18:51.009642

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e0970c86c22c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tourist_site', schema=None) as batch_op:
        batch_op.add_column(sa.Column('average_rating', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tourist_site', schema=None) as batch_op:
        batch_op.drop_column('average_rating')

    # ### end Alembic commands ###
