"""add atribute is_deteted in feedback

Revision ID: fef92e71547d
Revises: 4ca5d8e3796a
Create Date: 2025-11-01 11:35:38.759126

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fef92e71547d'
down_revision = '4ca5d8e3796a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('feedback', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_approved', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('is_deleted', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('feedback', schema=None) as batch_op:
        batch_op.drop_column('is_deleted')
        batch_op.drop_column('is_approved')

    # ### end Alembic commands ###
